DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = mqtt-demo
all: $(CONTIKI_PROJECT)

CONTIKI = ../..

CONTIKI_WITH_IPV6 = 1
CONTIKI_WITH_RPL = 1
LAST_UPDATE_LIMIT = 200

APPS += mqtt

include $(CONTIKI)/Makefile.include

